#PlayerAbilityLib configuration file
#
#If alwaysLogTamperWarnings is set to false, external update messages will be logged only once per game session
#Fri Aug 28 23:24:40 CEST 2026
alwaysLogTamperWarnings=true
